### PR TITLE
Improvements for PR #227

### PR DESCRIPTION
**Pull request by Darsstar**
Improvements for https://github.com/vaadin/cdi/pull/227

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/cdi/229)

### CODE REVIEW

**Comment by tsuoanttila** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-cdi/src/main/java/com/vaadin/cdi/CDIUIProvider.java, line 143 at r1](https://reviewable.io:443/reviews/vaadin/cdi/229#-KzccnbpdqDzJDLU59qy:-KzccnbpdqDzJDLU59qz:b-edcc40) ([raw file](https://github.com/vaadin/cdi/blob/a5ac0d9d22dc8e6f7c041c004208223d30f6065e/vaadin-cdi/src/main/java/com/vaadin/cdi/CDIUIProvider.java#L143)):*
> ```Java
>         }
> 
>         return pathInfo.equals("/") || pathInfo.startsWith("/!");
> ```

so the `!`is used as a separator between the UI path and the view? Is there somewhere support in the framework itself for this functionality?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/cdi/229)*

**Comment by tsuoanttila** [comment]
Reviewed 3 of 4 files at r1.
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/cdi/229)*

**Comment by Darsstar** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-cdi/src/main/java/com/vaadin/cdi/CDIUIProvider.java, line 143 at r1](https://reviewable.io:443/reviews/vaadin/cdi/229#-KzccnbpdqDzJDLU59qy:-KzctPh3l5BgLQxLSyMn:b-fg5n73) ([raw file](https://github.com/vaadin/cdi/blob/a5ac0d9d22dc8e6f7c041c004208223d30f6065e/vaadin-cdi/src/main/java/com/vaadin/cdi/CDIUIProvider.java#L143)):*
>so the `!` is used as a separator between the UI path and the view?

Yes.

>Is there somewhere support in the framework itself for this functionality?

No.  It's just a view name that starts with the `!`. And for every `@CDIView("<x>")` `CDIViewProvider` will be able to locate views `<x>` and `!<x>`.

`CDIUIProvider#parseUIMapping(String)` method seems to have been written to parse URIs with a scheme based on the tests.  But since before the first 1.0.0 version it has been parsing pathInfo strings. (`getRequestPathInfo()` was used until a certain point, could that have contained the fragment part?) So UI mappings containing a `!` have effectively been disallowed.
Therefore it should't break anything.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/cdi/229)*

**Comment by tsuoanttila** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-cdi/src/main/java/com/vaadin/cdi/CDIViewProvider.java, line 87 at r2](https://reviewable.io:443/reviews/vaadin/cdi/229#-KzhJvXmkxgR6dunnXGs:-KzhJvXmkxgR6dunnXGt:bhrjail) ([raw file](https://github.com/vaadin/cdi/blob/8373e91bf5fbf098497e158465ba53e5e71819e0/vaadin-cdi/src/main/java/com/vaadin/cdi/CDIViewProvider.java#L87)):*
> ```Java
>             if (specifiedViewName != null && !specifiedViewName.isEmpty()) {
>                 if (viewAndParameters.startsWith("!")) {
>                     specifiedViewName = "!".concat(specifiedViewName);
> ```

Now this is matching `viewName` and `!viewName` and below in the `getViewBean` it's stripping the `!` from the view name. Should we just simplify it and remove the `!` from the start of `viewAndParameters` and handle view names without `!`? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/cdi/229)*

**Comment by Darsstar** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-cdi/src/main/java/com/vaadin/cdi/CDIViewProvider.java, line 87 at r2](https://reviewable.io:443/reviews/vaadin/cdi/229#-KzhJvXmkxgR6dunnXGs:-KzhR5zqye_NsFANoJOc:by27xql) ([raw file](https://github.com/vaadin/cdi/blob/8373e91bf5fbf098497e158465ba53e5e71819e0/vaadin-cdi/src/main/java/com/vaadin/cdi/CDIViewProvider.java#L87)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Now this is matching `viewName` and `!viewName` and below in the `getViewBean` it's stripping the `!` from the view name. Should we just simplify it and remove the `!` from the start of `viewAndParameters` and handle view names without `!`? 
</blockquote></details>

`getViewBean(String)` is also used by `getView(String)`. `Navigator` will pass the return value from `getViewName(String)` to `getView(String)`, and later on expects that if the return value of `getViewName(String)` is shorter than the navigation state `navigationState.startsWith(longestViewNameProvider.getViewName(navigationState))` is true.
So I'm convinced it has to be added.

Or are you suggesting not supporting view names containing `!` at all?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/cdi/229)*

**Comment by Darsstar** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-cdi/src/main/java/com/vaadin/cdi/CDIViewProvider.java, line 87 at r2](https://reviewable.io:443/reviews/vaadin/cdi/229#-KzhJvXmkxgR6dunnXGs:-KzhTRRBJVMANfQJsfRo:bqmbqc8) ([raw file](https://github.com/vaadin/cdi/blob/8373e91bf5fbf098497e158465ba53e5e71819e0/vaadin-cdi/src/main/java/com/vaadin/cdi/CDIViewProvider.java#L87)):*
<details><summary><i>Previously, Darsstar (Dos Moonen) wrote…</i></summary><blockquote>

`getViewBean(String)` is also used by `getView(String)`. `Navigator` will pass the return value from `getViewName(String)` to `getView(String)`, and later on expects that if the return value of `getViewName(String)` is shorter than the navigation state `navigationState.startsWith(longestViewNameProvider.getViewName(navigationState))` is true.
So I'm convinced it has to be added.

Or are you suggesting not supporting view names containing `!` at all?
</blockquote></details>

s/containing `!` at all/starting with `!` at all

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/cdi/229)*

**Comment by Darsstar** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-cdi/src/main/java/com/vaadin/cdi/CDIViewProvider.java, line 87 at r2](https://reviewable.io:443/reviews/vaadin/cdi/229#-KzhJvXmkxgR6dunnXGs:-KzhsQ1z72sh4eELGRMi:b-8padv5) ([raw file](https://github.com/vaadin/cdi/blob/8373e91bf5fbf098497e158465ba53e5e71819e0/vaadin-cdi/src/main/java/com/vaadin/cdi/CDIViewProvider.java#L87)):*
<details><summary><i>Previously, Darsstar (Dos Moonen) wrote…</i></summary><blockquote>

s/containing `!` at all/starting with `!` at all
</blockquote></details>

I simplified things a bit.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/cdi/229)*

**Comment by tsuoanttila** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/cdi/229)*

**Comment by Darsstar** [comment]
Just a friendly reminder this PR targets the pushstate_navigation branch, which is the 'from' for your PR.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/cdi/229#-:-KziRwOzZLZl34XctIjl:bg4v12g)*

**Comment by tsuoanttila** [comment]
I am well aware of that. Also the fact that I'm running out of hours in my week. Let's hope to get a release progressing this week.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/cdi/229#-:-KzwceGDn0vFUb3bTS3z:b-grudir)*

**Pull request merged**
