### PR TITLE
View context strategy annotations

### PR DESCRIPTION
**Pull request by kumm**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/cdi/233)

### CODE REVIEW

**Comment by tsuoanttila** [comment]
Review status: 0 of 15 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/cdi/233#-L-Vjgw4jRsXFB3TCst1:-L-Vjgw4jRsXFB3TCst2:b4kqi2g) (no related file):*
This patch has a lot of test errors. Do you have time to look at them?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/cdi/233)*

**Comment by kumm** [comment]
Review status: 0 of 15 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/cdi/233#-L-Vjgw4jRsXFB3TCst1:-L-WFVHAe54FZ-wqwgmb:bxc7u09) (no related file):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

This patch has a lot of test errors. Do you have time to look at them?
</blockquote></details>

sorry, fixed in 26bfc2c

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/cdi/233)*

**Comment by tsuoanttila** [comment]
Did a partial review. Still need to consider the naming and the JavaDocs on the annotations.

---

Reviewed 9 of 15 files at r1, 1 of 1 files at r2.
Review status: 10 of 15 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-cdi/src/main/java/com/vaadin/cdi/internal/ViewContextStrategies.java, line 36 at r2](https://reviewable.io:443/reviews/vaadin/cdi/233#-L-Wc2lTUB8WUrEEtDaN:-L-Wc2lUonhNWFupzx6w:b8d8vpv) ([raw file](https://github.com/vaadin/cdi/blob/26bfc2caa51a251f2aaeffbb46728c642bc6ca96/vaadin-cdi/src/main/java/com/vaadin/cdi/internal/ViewContextStrategies.java#L36)):*
> ```Java
>  * Holder class for ViewContextStrategy implementations.
>  */
> public class ViewContextStrategies {
> ```

What's the usage of this? As it's part of `internal` subpackage, could the visibility be limited?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/cdi/233#-:-L-WdXKad3Fw76BKdcni:b-gujdta)*

**Comment by kumm** [comment]
Review status: 10 of 15 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-cdi/src/main/java/com/vaadin/cdi/internal/ViewContextStrategies.java, line 36 at r2](https://reviewable.io:443/reviews/vaadin/cdi/233#-L-Wc2lTUB8WUrEEtDaN:-L-XCv_fCiQ57K2K8QvM:b-nsraw4) ([raw file](https://github.com/vaadin/cdi/blob/26bfc2caa51a251f2aaeffbb46728c642bc6ca96/vaadin-cdi/src/main/java/com/vaadin/cdi/internal/ViewContextStrategies.java#L36)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

What's the usage of this? As it's part of `internal` subpackage, could the visibility be limited?
</blockquote></details>

It have to be public, because static subclasses are instantiated by CDI.
It is just a 'package' for ViewContextStragegy annotations. Could be a real package too.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/cdi/233)*

**Comment by tsuoanttila** [comment]
@legioth Care to give your opinions on the naming of the annotations?

---

Review status: 10 of 15 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-cdi/src/main/java/com/vaadin/cdi/internal/ViewContextStrategies.java, line 36 at r2](https://reviewable.io:443/reviews/vaadin/cdi/233#-L-Wc2lTUB8WUrEEtDaN:-L-_skV1PerRyFF5ybE8:b2dzqkw) ([raw file](https://github.com/vaadin/cdi/blob/26bfc2caa51a251f2aaeffbb46728c642bc6ca96/vaadin-cdi/src/main/java/com/vaadin/cdi/internal/ViewContextStrategies.java#L36)):*
<details><summary><i>Previously, kumm wrote…</i></summary><blockquote>

It have to be public, because static subclasses are instantiated by CDI.
It is just a 'package' for ViewContextStragegy annotations. Could be a real package too.

</blockquote></details>

OK. I think it's "hidden" enough as it is now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/cdi/233#-:-L-_sxACKXdwlkAU6Wqa:b-u26r8d)*

**Comment by Legioth** [comment]
I'm not entirely sure about the `Driven` prefix.

What about these names? 
* `ViewContextByName`
* `ViewContextByNameAndParameters`
* `ViewContextByNavigation`

---

Review status: 10 of 15 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-cdi/src/main/java/com/vaadin/cdi/viewcontextstrategy/ViewContextStrategy.java, line 80 at r2](https://reviewable.io:443/reviews/vaadin/cdi/233#-L-jumCj-Nd0F_Gz23gs:-L-jumCj-Nd0F_Gz23gt:btgoac7) ([raw file](https://github.com/vaadin/cdi/blob/26bfc2caa51a251f2aaeffbb46728c642bc6ca96/vaadin-cdi/src/main/java/com/vaadin/cdi/viewcontextstrategy/ViewContextStrategy.java#L80)):*
> ```Java
>      * @return {@code true} to hold context open; {@code false} to release it
>      */
>     boolean contains(String viewName, String parameters);
> ```

This method name feels quite unclear to me since the strategy itself doesn't "contain" anything.

What about `inCurrentContext` instead?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/cdi/233#-:-L-jvbrFva1HFqirgT7e:b5ycgwv)*

**Comment by pleku** [comment]
:lgtm:

---

Reviewed 16 of 16 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/cdi/233#-:-L2VAu-6b4QCtyGDkfCk:bnfp4nl)*

**Pull request merged**
