### PR TITLE
Fixing issue of UIScoped beans not being freed according to UI lifecy…

### PR DESCRIPTION
**Pull request by TatuLund**
…cle, which caused memory leak with Wildfly / Weld when using multiple UIs per session (e.g. multpiple browser windows), fix is rebased and adapted from original fix by kumm https://github.com/vaadin/cdi/pull/195

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/cdi/231)

### CODE REVIEW

**Comment by tsuoanttila** [comment]
Reviewed 18 of 18 files at r1.
Review status: all files reviewed at latest revision, 18 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/cdi/231#-L329f-MljvtMw8plPGX:-L329f-NAGdh7F7trtXG:b-tbpjf0) (no related file):*
Lots of formatting related issues.

---

*[vaadin-cdi/pom.xml, line 248 at r1](https://reviewable.io:443/reviews/vaadin/cdi/231#-L3273aFgj-4FxK39-1E:-L3273aFgj-4FxK39-1F:b-75ywm7) ([raw file](https://github.com/vaadin/cdi/blob/619ebce53f277d86d2ca5557a0a301474616fb26/vaadin-cdi/pom.xml#L248)):*
> ```XML
>                                 <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
>                                 <jboss.home>${project.build.directory}/wildfly-10.1.0.Final</jboss.home>
>                                 <arguillian.launch>wildfly</arguillian.launch>
> ```

why is this needed?

---

*[vaadin-cdi/src/main/java/com/vaadin/cdi/CDIViewProvider.java, line 307 at r1](https://reviewable.io:443/reviews/vaadin/cdi/231#-L320dmmo5Fyadzj4cME:-L320dmmo5Fyadzj4cMF:bs5wf9o) ([raw file](https://github.com/vaadin/cdi/blob/619ebce53f277d86d2ca5557a0a301474616fb26/vaadin-cdi/src/main/java/com/vaadin/cdi/CDIViewProvider.java#L307)):*
> ```Java
> 
>             if (Dependent.class.isAssignableFrom(viewBean.getScope())) {
>             	dependentViewCreationalContext = creationalContext;
> ```

inconsistent whitespacing, extra space at end of rows

---

*[vaadin-cdi/src/main/java/com/vaadin/cdi/internal/AbstractVaadinContext.java, line 198 at r1](https://reviewable.io:443/reviews/vaadin/cdi/231#-L321NwroTWAdHSl3CQB:-L321NwroTWAdHSl3CQC:bzi5tou) ([raw file](https://github.com/vaadin/cdi/blob/10a6b177d422d94b1be597701bc2ec5a883635f5/vaadin-cdi/src/main/java/com/vaadin/cdi/internal/AbstractVaadinContext.java#L198)):*
> ```Java
>                 Map<Integer, UIData> map = sessionData.getUiDataMap();
>                 for (UIData uiData : new ArrayList<UIData>(map.values())) {
>                     dropUIData(sessionData, uiData.getUiId());
> ```

dropUIData not needed anymore?

---

*[vaadin-cdi/src/main/java/com/vaadin/cdi/internal/AbstractVaadinContext.java, line 200 at r1](https://reviewable.io:443/reviews/vaadin/cdi/231#-L320slsNWuavmIkiW-w:-L320slsNWuavmIkiW-x:brvx7bv) ([raw file](https://github.com/vaadin/cdi/blob/619ebce53f277d86d2ca5557a0a301474616fb26/vaadin-cdi/src/main/java/com/vaadin/cdi/internal/AbstractVaadinContext.java#L200)):*
> ```Java
>         if (sessionData != null) {
>             synchronized (sessionData) {
>             	Collection<ContextualStorage> storages = sessionData.storageMap.values();
> ```

tabs instead of spaces

---

*[vaadin-cdi/src/main/java/com/vaadin/cdi/internal/AbstractVaadinContext.java, line 215 at r1](https://reviewable.io:443/reviews/vaadin/cdi/231#-L321n87ruqhC9Ir4QCO:-L321n87ruqhC9Ir4QCP:b-9j56wf) ([raw file](https://github.com/vaadin/cdi/blob/619ebce53f277d86d2ca5557a0a301474616fb26/vaadin-cdi/src/main/java/com/vaadin/cdi/internal/AbstractVaadinContext.java#L215)):*
> ```Java
>         	if (contextual instanceof UIContextual && ((UIContextual) contextual).getUiId() == uiId) {
>         		final ContextualStorage storage = storageMap.remove(contextual);
>         		destroyAllActive(storage);
> ```

tabs vs. spaces

---

*[vaadin-cdi/src/main/java/com/vaadin/cdi/internal/AbstractVaadinContext.java, line 259 at r1](https://reviewable.io:443/reviews/vaadin/cdi/231#-L327SZ5RTqqGNMQiX6l:-L327SZ5RTqqGNMQiX6m:b-9okk2s) ([raw file](https://github.com/vaadin/cdi/blob/619ebce53f277d86d2ca5557a0a301474616fb26/vaadin-cdi/src/main/java/com/vaadin/cdi/internal/AbstractVaadinContext.java#L259)):*
> ```Java
>                         false);
>                 if (sessionData != null) {
>                     dropUIData(sessionData, event.getUiId());
> ```

Should this also do some bigger clean up or is the dropUIData enough?

---

*[vaadin-cdi/src/main/java/com/vaadin/cdi/internal/ViewScopedContext.java, line 152 at r1](https://reviewable.io:443/reviews/vaadin/cdi/231#-L323Irw6kdcwfr7uKri:-L323Irw6kdcwfr7uKrj:bdstlxm) ([raw file](https://github.com/vaadin/cdi/blob/10a6b177d422d94b1be597701bc2ec5a883635f5/vaadin-cdi/src/main/java/com/vaadin/cdi/internal/ViewScopedContext.java#L152)):*
> ```Java
>             if (contextual.uiId == uiId
>                     && !contextual.viewIdentifier.equals(activeViewName)) {
>                 getLogger().fine(
> ```

Should the logging be still in place? 

---

*[vaadin-cdi/src/test/java/com/vaadin/cdi/UINormalDestroyTest.java, line 11 at r1](https://reviewable.io:443/reviews/vaadin/cdi/231#-L328CDQVD33iOizukE_:-L328CDQVD33iOizukEa:b-1m9ux7) ([raw file](https://github.com/vaadin/cdi/blob/619ebce53f277d86d2ca5557a0a301474616fb26/vaadin-cdi/src/test/java/com/vaadin/cdi/UINormalDestroyTest.java#L11)):*
> ```Java
>         return DestroyNormalUI.class;
>     }
> }
> ```

missing newline

---

*[vaadin-cdi/src/test/java/com/vaadin/cdi/ViewDestroyNormalUITest.java, line 11 at r1](https://reviewable.io:443/reviews/vaadin/cdi/231#-L328DukdMGyBYZsYYEz:-L328Dul3jWWPqUAp4xn:b-1m9ux7) ([raw file](https://github.com/vaadin/cdi/blob/619ebce53f277d86d2ca5557a0a301474616fb26/vaadin-cdi/src/test/java/com/vaadin/cdi/ViewDestroyNormalUITest.java#L11)):*
> ```Java
>         return DestroyViewNormalUI.class;
>     }
> }
> ```

missing newline

---

*[vaadin-cdi/src/test/java/com/vaadin/cdi/ViewDestroyTest.java, line 70 at r1](https://reviewable.io:443/reviews/vaadin/cdi/231#-L328GOXQ5m4k6VKbAKm:-L328GOXQ5m4k6VKbAKn:b-1m9ux7) ([raw file](https://github.com/vaadin/cdi/blob/619ebce53f277d86d2ca5557a0a301474616fb26/vaadin-cdi/src/test/java/com/vaadin/cdi/ViewDestroyTest.java#L70)):*
> ```Java
>     }
> 
> }
> ```

missing newline

---

*[vaadin-cdi/src/test/java/com/vaadin/cdi/uis/DestroyUI.java, line 39 at r1](https://reviewable.io:443/reviews/vaadin/cdi/231#-L328rPVuSiDj4H82VSE:-L328rPVuSiDj4H82VSF:b-k10qpq) ([raw file](https://github.com/vaadin/cdi/blob/619ebce53f277d86d2ca5557a0a301474616fb26/vaadin-cdi/src/test/java/com/vaadin/cdi/uis/DestroyUI.java#L39)):*
> ```Java
>     @Inject
>     UIScopedBean bean;
>     
> ```

extra spaces

---

*[vaadin-cdi/src/test/java/com/vaadin/cdi/uis/DestroyViewNormalUI.java, line 9 at r1](https://reviewable.io:443/reviews/vaadin/cdi/231#-L328jTuKacSrOvXayHP:-L328jTuKacSrOvXayHQ:b-1m9ux7) ([raw file](https://github.com/vaadin/cdi/blob/619ebce53f277d86d2ca5557a0a301474616fb26/vaadin-cdi/src/test/java/com/vaadin/cdi/uis/DestroyViewNormalUI.java#L9)):*
> ```Java
> @NormalUIScoped
> public class DestroyViewNormalUI extends DestroyViewUI {
> }
> ```

missing newline

---

*[vaadin-cdi/src/test/java/com/vaadin/cdi/uis/DestroyViewUI.java, line 115 at r1](https://reviewable.io:443/reviews/vaadin/cdi/231#-L328ujbzQgkkyowze3j:-L328ujbzQgkkyowze3k:b-1m9ux7) ([raw file](https://github.com/vaadin/cdi/blob/619ebce53f277d86d2ca5557a0a301474616fb26/vaadin-cdi/src/test/java/com/vaadin/cdi/uis/DestroyViewUI.java#L115)):*
> ```Java
> 
> 
> }
> ```

missing newline

---

*[vaadin-cdi/src/test/java/com/vaadin/cdi/views/UIScopedView.java, line 35 at r1](https://reviewable.io:443/reviews/vaadin/cdi/231#-L328xj6y0jjzgYsNkzs:-L328xj6y0jjzgYsNkzt:b-g1kqjy) ([raw file](https://github.com/vaadin/cdi/blob/619ebce53f277d86d2ca5557a0a301474616fb26/vaadin-cdi/src/test/java/com/vaadin/cdi/views/UIScopedView.java#L35)):*
> ```Java
>     @Inject
>     private DependentBean dependentBean;
>     
> ```

extra whitespace

---

*[vaadin-cdi/src/test/java/com/vaadin/cdi/views/UIScopedView.java, line 80 at r1](https://reviewable.io:443/reviews/vaadin/cdi/231#-L329-W9DanvMwGzZOyH:-L329-W9DanvMwGzZOyI:bmlt0ex) ([raw file](https://github.com/vaadin/cdi/blob/619ebce53f277d86d2ca5557a0a301474616fb26/vaadin-cdi/src/test/java/com/vaadin/cdi/views/UIScopedView.java#L80)):*
> ```Java
>     	@Inject
>     	Counter counter;
> ```

tabs vs. spaces

---

*[vaadin-cdi/src/test/java/com/vaadin/cdi/views/ViewScopedView.java, line 35 at r1](https://reviewable.io:443/reviews/vaadin/cdi/231#-L3291jI9Ci4HPeZ7Qou:-L3291jI9Ci4HPeZ7Qov:b-g1kqjy) ([raw file](https://github.com/vaadin/cdi/blob/619ebce53f277d86d2ca5557a0a301474616fb26/vaadin-cdi/src/test/java/com/vaadin/cdi/views/ViewScopedView.java#L35)):*
> ```Java
>     @Inject
>     private DependentBean dependentBean;
>     
> ```

extra whitespace

---

*[vaadin-cdi/src/test/java/com/vaadin/cdi/views/ViewScopedView.java, line 84 at r1](https://reviewable.io:443/reviews/vaadin/cdi/231#-L329337PWFHioHtZA_S:-L329337PWFHioHtZA_T:bs8uwax) ([raw file](https://github.com/vaadin/cdi/blob/619ebce53f277d86d2ca5557a0a301474616fb26/vaadin-cdi/src/test/java/com/vaadin/cdi/views/ViewScopedView.java#L84)):*
> ```Java
>     	@PreDestroy
>     	private void preDestroy() {
>     		counter.increment(DESTROY_COUNT);
> ```

tabs vs. spaces + extra whitespace

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/cdi/231)*

**Comment by TatuLund** [comment]
*[vaadin-cdi/pom.xml, line 248 at r1](https://reviewable.io:443/reviews/vaadin/cdi/231#-L3273aFgj-4FxK39-1E:-L3cWDmC3k9osarBAFqc:btgg2px) ([raw file](https://github.com/vaadin/cdi/blob/619ebce53f277d86d2ca5557a0a301474616fb26/vaadin-cdi/pom.xml#L248)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

why is this needed?
</blockquote></details>

 This is most likely related to new test cases and their assertions.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/cdi/231)*

**Comment by tsuoanttila** [comment]
Reviewed 10 of 10 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/cdi/231#-L3hOPF6tQX_wSvepuyZ:-L3hOPF6tQX_wSvepuy_:b-vd8orz) (no related file):*
Blocking comment for a moment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/cdi/231)*

**Comment by tsuoanttila** [comment]
Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/cdi/231)*

**Comment by elmot** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/cdi/231#-:-L3h_3E0Uz2W6aNT2Zia:bnfp4nl)*

**Pull request merged**
