### PR TITLE
Update version number, dependencies etc. for Vaadin 8

### PR DESCRIPTION
**Pull request by hesara**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/cdi/185)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/cdi/185)*

**Comment by denis-anisimov** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/cdi/185)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/cdi/185)*

**Comment by hesara** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/cdi/185)*

**Pull request merged**
