### PR TITLE
Some CDIView annotation cleanup

### PR DESCRIPTION
**Pull request by kumm**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/cdi/211)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/cdi/211)*

**Comment by hesara** [comment]
Is this redundant with #212?

**Comment by kumm** [comment]
#212 based on this branch. Rebase now, or after this PR merged?

**Comment by hesara** [comment]
Ok, merging this so that #212 can be updated to be on top of this.

**Pull request merged**
