### PR TITLE
Update version for a Vaadin Framework 8 version

### PR DESCRIPTION
**Pull request by Artur-**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/cdi/175)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/cdi/175)*

**Comment by pleku** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/cdi/175#-KTxbagW2pnbsdojYLvj:-KTxbagW2pnbsdojYLvk:bgqgz3y) (no related file):*
Why doesn't this update the used vaadin version in the submodule POM ???
Also the version for cdi/pom.xml is still 1.0-SNAPSHOT ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/cdi/175)*

**Comment by Artur-** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/cdi/175#-KTxbagW2pnbsdojYLvj:-KTxmQ4GO3gk-QBnCgGk:b-xd8bl0) (no related file):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary>
> Why doesn't this update the used vaadin version in the submodule POM ???
> Also the version for cdi/pom.xml is still 1.0-SNAPSHOT ?
</details>
I see, it's one of these projects which have a parent pom but the parent pom is not used...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/cdi/175)*

**Comment by hesara** [comment]
More complete changes for this in the vaadin-8 branch.

**Pull request closed without merging**
