### PR TITLE
UIBean factor out, more fixes for contextual instance destroy

### PR DESCRIPTION
**Pull request by kumm**
This pull request is based on #183 . Starting at commit b2291b3.
Contents:
- a test, and fix for #176 ( first two commit is rebased from pull request #178 )
- a refactor to drop UIBean concept. I found this concept makes hard to properly destroy contextual instances.
- tests, and fixes to more issues related to destroying contextual instances. #169 #156 #158 .

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/cdi/184)

### CODE REVIEW

**Comment by doggy-dev** [comment]
It would be great if someone from Vaadin could review this pull request. I hope this fixes some long due bugs.

**Comment by macjuan** [comment]
In order to get this PR reviewed faster it would be good if this PR could be split into set of smaller changes.

**Comment by hesara** [comment]
I'll review the test changes in #183, which should allow rebasing and separating the functional changes.

**Comment by hesara** [comment]
Added review comments to #183. Please take a look at them and rebase #183 on top of the current master (might lead to some conflict resolution as master has a few test related changes, you revert some of those if your patch does the same things better). Once #183 is merged, please rebase #184 changes on top of the latest master. If there are logically separate changes, splitting those to separate PRs might also speed things up a bit.

**Comment by kumm** [comment]
Ok, i will split it to 4 PR.

**Comment by moldowan** [comment]
@kumm it's good to see that someone is taking a stab at this.
You didn't have the time yet to create separate PRs, did you?

**Comment by kumm** [comment]
@moldowan: i'm waiting for #183 to be merged. I'm going to send my PRs based on the new master, as suggested by @hesara

**Comment by hesara** [comment]
Parts of this PR were integrated as separate PRs, and parts were found to be problematic in the context of PR #194. This PR can probably be closed and replaced with a new approach later.

**Comment by kumm** [comment]
closing it

**Pull request closed without merging**
