### PR TITLE
remove out-of-scope components from parent

### PR DESCRIPTION
**Pull request by roeltje25**
When HasElements / Components are out of scope they are destroyed, but are not removed from their parents. In case of UIScoped parent layouts with RouteScoped router content for example, this will result in these elements remaining in the component tree with undesirable results. This change checks if objects that will become out of scope and should be destroyed are Component or HasElement and will remove them from their parent to ensure they can ultimately be garbage collected.

This pull request is associated to issue #345 and related to issue #324

### CODE REVIEW

**Comment by roeltje25** [comment]
am creating associated issue at this moment

**Comment by roeltje25** [comment]
Denis, thank you for your comments. ALthough, reading your comments it seems you are refering to my proposed patch in #324. This pullrequest is actually a different angle to the problem and only handles removing Out-of-scope components from their parent. Something which seems to me to be strange that is is not the case already. But we discussed this in #324 to some point already.

**Comment by denis-anisimov** [comment]
Well, yes. I kept in mind the issue with router.

But does this PR has any sense at all? 
How the component may be destroyed if it's directly referenced from another bean (regardless of any UI consideration).

**Comment by roeltje25** [comment]
Without this PR the RouteScoped component is removed from the scope, but it will remain attached to the UIScoped parent layout. This PR will make sure it can get destroyed by making it remove it from the parent first. Attaching to the parent layout is handled by the framework, so developers do not explicitly think about removing it after the child component is out of scope. This will make the child component get removed when it is out of scope. which to me and my colleagues clearly makes a lot of sense. How does it seem non-sensical to you? Perhaps we can ask another set of eyes to have a look. It seems to me that perhaps I am not explaining myself correctly.

**Comment by roeltje25** [comment]
This has been running in production in our servers for a month now and running exactly as we expect it to. Is there a possiblity for another review?

It seems ownership of attaching and detaching components for managed beans like @RouteScoped and @UIScoped beans should be with the framework not the developer of the application, that would go against the point of "managed beans". As it stands @RouteScoped components are not removed from @UISCoped parent layouts when the @RouteScoped bean goes out of scope by moving to another route. It should as the documentation of @RouteScoped mentions that in the absence of @RouteScopeOwner annotations the route scope owner is the bean itself (which is out of scope after moving to another route).

Looking forward to a review....

**Comment by mshabarov** [comment]
Thanks for contribution, @roeltje25 !
The issue has been fixed on the [Flow side](https://github.com/vaadin/flow/pull/10973) based on your [suggestion](https://github.com/vaadin/cdi/issues/324#issuecomment-641778167).
Thus, I close this PR.

**Comment by roeltje25** [comment]
You are very welcome. And I am very happy this has been solved.

Op ma 17 mei 2021 13:50 schreef Mikhail Shabarov ***@***.***>:

**Pull request closed without merging**
