### PR TITLE
fix for closed UI cleanup

### PR DESCRIPTION
**Pull request by kumm**
It's a fix for #176.
Part 1 of #184

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/cdi/193)

### CODE REVIEW

**Comment by hesara** [comment]
The change itself looks ok, but some comments about tests where you could perhaps comment on the way things are done, and this could be picked/rebased on top of master as the ShiroTest change was already merged there.

---

Reviewed 5 of 7 files at r1.
Review status: 5 of 7 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[vaadin-cdi/src/test/java/com/vaadin/cdi/UIDestroyTest.java, line 41 at r1](https://reviewable.io:443/reviews/vaadin/cdi/193#-KbiG5I0_XiqgsxcnTv5:-KbiG5I0_XiqgsxcnTv6:blue0wr) ([raw file](https://github.com/vaadin/cdi/blob/b1b322eb8fd88bffacd79f6257f5d81735d4396c/vaadin-cdi/src/test/java/com/vaadin/cdi/UIDestroyTest.java#L41)):*
> ```Java
>         assertDestroyCount(0);
> 
>         Thread.sleep(5000); //AbstractVaadinContext.CLEANUP_DELAY
> ```

if this is the exact delay, this test might be somewhat fragile (not sure if an issue)

---

*[vaadin-cdi/src/test/java/com/vaadin/cdi/uis/DestroyUI.java, line 71 at r1](https://reviewable.io:443/reviews/vaadin/cdi/193#-KbiGKb3BKPVzuVBM5u7:-KbiGKb3BKPVzuVBM5u8:b-1o9u7v) ([raw file](https://github.com/vaadin/cdi/blob/b1b322eb8fd88bffacd79f6257f5d81735d4396c/vaadin-cdi/src/test/java/com/vaadin/cdi/uis/DestroyUI.java#L71)):*
> ```Java
>             @Override
>             public void buttonClick(Button.ClickEvent event) {
>                 final Navigator navigator = new Navigator(DestroyUI.this, new ViewDisplay() {
> ```

unusual pattern for using the navigator (usually set up for the UI once at initialization), so not quite sure how well this test corresponds to a typical use case - although this might correspond more or less to a "set up navigator at login" case

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/cdi/193#-:-KbiHFMzxPuVKfkyMTeM:b-kc1e79)*

**Comment by kumm** [comment]
> if this is the exact delay, this test might be somewhat fragile (not sure if an issue)
Theoretically you are right. If opening the new UI, and processing the navigation click request executes under less than a millisecond, than it should fail. Who knows, cpus are getting faster and faster :)
Going to increment it.
What do you think increasing the visibilitiy of AbstractVaadinContext.CLEANUP_DELAY for test purpose would be better then duplicating the value?

**Comment by kumm** [comment]
> unusual pattern for using the navigator (usually set up for the UI once at initialization), so not quite sure how well this test corresponds to a typical use case - although this might correspond more or less to a "set up navigator at login" case

Indeed it's a bit unusual, but i have a reason.
Creating a navigator in init causes a navigation in com.vaadin.ui.UI#doInit. (Kickstarting the navigation)
I want to avoid any other navigation to be sure my navigation causes the cleanup.
Additionally i would have to provide a root view, or an error view to avoid the IllegalStateException would be caused by this kickstart navigation.

By the way this pattern can be found in other test UIs already (NoViewProviderNavigationUI, InstrumentedUI)

**Comment by kumm** [comment]
rebased onto master

**Comment by hesara** [comment]
:lgtm: - I suppose we can merge this as is

---

Reviewed 2 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[vaadin-cdi/src/test/java/com/vaadin/cdi/UIDestroyTest.java, line 41 at r1](https://reviewable.io:443/reviews/vaadin/cdi/193#-KbiG5I0_XiqgsxcnTv5:-KboKsHZqW1Ir-s3RndO:bgji2ij) ([raw file](https://github.com/vaadin/cdi/blob/b1b322eb8fd88bffacd79f6257f5d81735d4396c/vaadin-cdi/src/test/java/com/vaadin/cdi/UIDestroyTest.java#L41)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

if this is the exact delay, this test might be somewhat fragile (not sure if an issue)
</blockquote></details>

probably not too likely to fail the test; the value could also be made public but ok as-is

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/cdi/193#-:-KboLEeUn5fMzcUPxCcQ:b-6zh3wa)*

**Pull request merged**
