### PR TITLE
Update Readme and Travis after creating new branch for 3.0

### PR DESCRIPTION
**Pull request by pekam**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/cdi/245)

### CODE REVIEW

**Comment by elmot** [comment]
Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---

*[.travis.yml, line 10 at r1](https://reviewable.io/reviews/vaadin/cdi/245#-LDv5COl2TJ_aO2e2Bg7:-LDv5COm54uVKx3ZXSsT:ba24bie) ([raw file](https://github.com/vaadin/cdi/blob/ad57882bc01d16e85e709d764c06faff478f259b/.travis.yml#L10)):*
> ```YAML
>   only:
>   - 3.0
>   - 2.0
> ```

I am not sure about 1.0, 2.0

---

*[README.md, line 6 at r1](https://reviewable.io/reviews/vaadin/cdi/245#-LDv5NQa47Wv9YnUk8dm:-LDv5NQa47Wv9YnUk8dn:b3b8847) ([raw file](https://github.com/vaadin/cdi/blob/ad57882bc01d16e85e709d764c06faff478f259b/README.md#L6)):*
> ```Markdown
> This branch is Vaadin Framework 8.2+ compatible. See other branches for other framework versions:
> * master for Vaadin 10
> * 2.0 for Vaadin Framework 8.0...8.1 versions
> ```

It seems to me it's better to have the comprehensive(=full) list of branches in every branch. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/cdi/245)*

**Comment by elmot** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/cdi/245)*

**Comment by pekam** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 6 at r1](https://reviewable.io/reviews/vaadin/cdi/245#-LDv5NQa47Wv9YnUk8dm:-LDv7nsw1YgizqZ05FyY:b-896fix) ([raw file](https://github.com/vaadin/cdi/blob/ad57882bc01d16e85e709d764c06faff478f259b/README.md#L6)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

It seems to me it's better to have the comprehensive(=full) list of branches in every branch. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/cdi/245)*

**Comment by elmot** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/cdi/245)*

**Pull request merged**
