### PR TITLE
feat: Retain routescoped parentlayouts on route change

### LINKED ISSUE #388: RouteScoped parent layouts shared between RouteScoped Routes are not preserved
Recently, the working of RouteScoped has been changed. If a bean has no RouteScopeOwner attached, the lifecycle is bound to the lower most RouteComponent in the navigation chain. Seems sensible.

However. Imagine that a parent RouterLayout with RoutePRefix "parent" has two child route components. "one" and "two". All are RouteScoped. When navigating from one to two using the above "new" logic would and indeed does move the parentlayout out of scope. But should not the ParentLayout in this case be retained within scope?

Indeed when I upgrade Vaadin CDI from 12.0.0 to 13.0.0 some of my code breaks because of exactly this change.

My suggestion / expectation would be that @RouteScoped router layouts would  have a RouteScopeOwner being itself, not the bottom-most target in the navigation chain. This way the RouterLAyouts are preserved when they are shared between subsequent navigation targets.

### PR DESCRIPTION
**Pull request by roeltje25**
## Description

When changing routes where a RouterLayout comes into play that has a RoutePrefix associated with it and where this routerlayout is annotated to be @RouteScoped the spec has changed between Vaadin CDI 12 and Vaadin CDI 13 so that strictly the @RouteScopeOwner is considered to be the innermost Route component. This broke our code where we were depending on the fact that these RouterLayouts would not be recreated. We had defined services which were RouteScoped and had a RouterLayout as RouteScopeOwner but this did not work anymore.

This proposed change will result in RouterLayouts of this kind to be considered to have themselves as  @RouteScopeOwner. This fits with the notion that the Route part which pertains to this RouterLayout does in fact not change.

So imagine a component A with Route "a" which has a RouterLayout component PARENT with routeprefix "parent". And a second component B which has the same parent, but its route is "b".

So in Vaadin CDI 12.0.0 navigation to /parent/a would instantiate PARENT and A and subsequently navigating to /parent/b would discard A and instantiate B. It would retain PARENT.

In Vaadin CDI 13.0.0 this did not work anymore. Instead navigation to /parent/a would still instantiate PARENT and A, but subsequently navigating to /parent/b would discard PARENT and B and instantiate PARENT and B again.

Fixes #388 

## Type of change

- [ ] Bugfix
- [x] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.
I did not get integration tests working at all on my windows machine. Using the internal Ubuntu installed in Windows it also failed. So I was not able to run any testing

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

### CODE REVIEW

**Comment by mshabarov** [comment]
@roeltje25 I'm able to achieve the behaviour you described (router layout instance is preserved) by adding `@RouteScoped` into it, as well as to the child routes. With no owner specified.
Here is a branch in starter project https://github.com/vaadin/skeleton-starter-flow-cdi/tree/route-layout-test, and here is my code:

```java
@Route("")
@RoutePrefix("parent")
@RouteScoped
public class ParentView extends VerticalLayout implements RouterLayout {

    public ParentView() {
        String uuid = UUID.randomUUID().toString();
        Paragraph paragraph = new Paragraph("parent layout = " + uuid);
        add(paragraph);
    }
}

@RouteScoped
@Route(value = "A", layout = ParentView.class)
public class ChildAView extends VerticalLayout {

    public ChildAView() {
        String uuid = UUID.randomUUID().toString();
        Paragraph paragraph = new Paragraph("child A = " + uuid);
        add(paragraph);
        add(new RouterLink("Go to B", ChildBView.class));
    }
}

@RouteScoped
@Route(value = "B", layout = ParentView.class)
public class ChildBView extends VerticalLayout {

    public ChildBView() {
        String uuid = UUID.randomUUID().toString();
        Paragraph paragraph = new Paragraph("child B = " + uuid);
        add(paragraph);
        add(new RouterLink("Go to A", ChildAView.class));
    }
}
```

And when I navigate between A and B via router link, I always get the same instance of parent layout:

Screenshot 2022-09-27 at 13 47 25
Screenshot 2022-09-27 at 13 47 33

**Comment by roeltje25** [comment]
Well for sure, it seems you are right. I had not come around to provide a
minimal example, but will try to "remove" our workaround and test our
product. It may be that somewhere along the way this got solved either in
Vaadin (CDI) or on our side. If I encounter the problem when I remove the
workaround, I will try to get a "failing" example, or otherwise close the
bug. Give me a few days to find the time!

Thank you for your input sofar! It is very much appreciated


Roel

--------------------------------------------
Roel Meeuws
Email: ***@***.***
Mob. phone: +31 (0)6 10 82 44 01
--------------------------------------------


Op di 27 sep. 2022 om 12:50 schreef Mikhail Shabarov <
***@***.***>:

**Comment by mshabarov** [comment]
@roeltje25 let's close this PR for now, if you find something that still needs this patch, feel free to reopen it and we'll discuss.

**Comment by roeltje25** [comment]
Actually,I had provided an example in the associated issue.: https://github.com/vaadin/cdi/issues/388#issuecomment-1272954457

**Comment by roeltje25** [comment]
this issue is marked as "waiting for author. But I have provided the asked demo for the issue in the linked issue 388.

**Comment by mshabarov** [comment]
Removed. Thanks for noticing.

**Comment by mcollovati** [comment]
@roeltje25 thanks for the contribution, and sorry for the review taking so long.

I checked the change, also with `@PreserveOnRefresh`, and it looks good to me.
I create branch #426 that adds a test to avoid future regressions.

Do you mind picking the commit in your PR? (I cannot push on it)

Otherwise, if you are busy, I can merge my PR and mention you as the author

**Comment by roeltje25** [comment]
will do right now (though I have to figure out how to do that)

**Comment by roeltje25** [comment]
have cherry picked it via github desktop. although the resulting list of commits is now a bit convoluted IMO. It could have been only three commits, but GitHub Desktop made it into 6. It works a bit differently from Eclipse...

**Comment by mcollovati** [comment]
Thank you! No problem for the 6 commits, we will squash them into a single one when merging

**Review by mcollovati — CHANGES_REQUESTED** [review]
Just some cleanup

**Review by mcollovati — APPROVED** [review]

**Pull request merged**
